### ISSUE TITLE
Palindrome Solution - Use of Ternary Operator?

### ISSUE THREAD

**Issue by SaintPeter** [luishendrix92/My-FreeCodeCamp-Path#1]
I was reviewing your solution here:
https://github.com/luishendrix92/My-FreeCodeCamp-Path/wiki/Bonfire:-Check-for-Palindromes

I'm trying to figure out why you did this:
```javascript
return (cleanStr === rev(cleanStr)) ? true : false;
```
In order for the ternary operator to work, the result must ALREADY be true or false.  The ```===``` operator returns true or false, making this statement functionally equivalent:
```javascript
return (cleanStr === rev(cleanStr));
```

**Comment by luishendrix92** [comment]
Oh I didn't know about that. I had always used the ternary operator to return strings or functions but never a boolean value.

Thanks for clarifying it.
